### ISSUE TITLE
Duplicated instances of a same app are open at once

### ISSUE THREAD

**Issue by seaneking** [quanglam2807/juli#23]
Think the fix for #19 introduced a different regression - opening an app that has already been opened creates a new instance, rather than reactivating the existing one.

What I expect to happen:
- Open Juli app
- Soft close juli app
- Open Juli app 
- Juli app reactivates a window

What actually happens:
- Open Juli app
- Soft close Juli app
- Open Juli app
- New instance created, so there's now two of the same app in my dock

Personal use-case: I use Alfred (similar to spotlight), so I frequently 'open' apps rather than reactivate them from the dock

**Comment by quanglam2807** [comment]
Electron API is quite limited so the solution I have now would quit the old instance instead of quitting the new one. :(

**Comment by seaneking** [comment]
This seems to be broken again, assuming #25 reintroduced a regression

**Comment by quanglam2807** [comment]
@seaneking The way I fixed was bad. I knew it was bad. I knew it. Anyway, let's wait for #32

**Comment by seaneking** [comment]
Sorry, but still happening for me on 2.1.1

![issue](https://user-images.githubusercontent.com/6374876/38416028-93b788d2-39bd-11e8-8bc8-6ca82074fb7e.gif)

¯\\_(ツ)_/¯

**Comment by quanglam2807** [comment]
@seanking One instance of Asana is already open, right? So what you expect is to have the Asana window shows up?
